### ISSUE TITLE
Dockerfile is missing

### ISSUE THREAD

**Issue by bhawdeadlydan** [jhipster/jhipster-sample-app-dotnetcore#1]
As part of README it is mentioned that to create a docker container we should run the following command

`docker build -f ./src/Jhipster/Dockerfile -t jhipster .`

However as part of the latest commit the Dockerfile has been deleted.

**Comment by nicolas63** [comment]
yes indeed I will fix this as soon as possible. (it's due to gitignore).
This repository is just the generated application can you open the issue on the repository of the generator ?  (https://github.com/jhipster/jhipster-dotnetcore)

**Comment by nicolas63** [comment]
it's fix with version 1.1.1 of the generator
