### ISSUE TITLE
Update to .NET 5 core and host on linux

### ISSUE THREAD

**Issue by weedkiller** [jhipster/jhipster-sample-app-dotnetcore#3]
Hello can you please update to the current .net 5 and also explain how to how on linux.

thanks

**Comment by nicolas63** [comment]
Hi, 
the project is generated by https://github.com/jhipster/jhipster-dotnetcore 
Can you open the issue on the generator ? 

For "explain how to how on linux" what do you mean ? How to build / deploy on linux ?
