### ISSUE TITLE
bug of jhipster entity <entity-name> (thanks for anyone's help)

### ISSUE THREAD

**Issue by MrWYG** [jhipster/jhipster-sample-app-dotnetcore#4]
https://jhipsternet.readthedocs.io/en/latest/Introduction/getting-started.html 
When I test this Getting Started(link above), after run the order : jhipster entity <entity-name>, got the bug below: 
• INFO! Error parsing options for generator jhipster-dotnetcore:entity, error: Error: This is a JHipster blueprint and should be used only like jhipster --blueprint dotnetcore
• ERROR! jhContext.setupEntityOptions is not a function
• TypeError: jhContext.setupEntityOptions is not a function
• at new module.exports (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\generators\entity\index.js:25:19)
• at Environment.instantiate (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:748:23)
• at Environment.create (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:720:17)
• at EntityGenerator.composeWith (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1182:42)
• at EntityGenerator._composeBlueprint (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:348:37)
• at C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:248:41
• at Array.forEach (<anonymous>)
• at EntityGenerator.instantiateBlueprints (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:247:18)
• at new EntityGenerator (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\entity\index.js:147:49)
• at Environment.instantiate (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:748:23)

**Comment by nicolas63** [comment]
Hello, sorry but this project is just a sample app generated by https://github.com/jhipster/jhipster-dotnetcore 
Can you open your issue here (https://github.com/jhipster/jhipster-dotnetcore/issues) please ? 
I close this
